databases:
  - name: postgresql
    ipAllowList: []

services:
  - type: web
    name: voteRemoteRails
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: voteRemoteRails
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - type: redis
        name: redis
        ipAllowList: []
        plan: free
        maxmemoryPolicy: noeviction